'use strict';

// Process-wide model PRICE TABLE ("what does this model cost per 1M tokens").
//
// WHY this module exists: an Auto Provider router has to compare candidate
// models by cost before it picks a lane, and that answer must not depend on
// which chat page is open, which vendor CLI happens to be installed, or on a
// network round trip inside a turn. So one reader of the price catalog lives
// here, and every other module asks it.
//
// Source of truth: models.dev (https://models.dev/api.json) — a public,
// community-maintained catalog of ~225 providers / ~8300 models, served with an
// ETag, reachable directly (no proxy). Shape:
//
//   { "<providerKey>": { id, name, models: { "<modelId>": { id, name,
//       cost: { input, output, cache_read, cache_write },   // USD per 1M tokens, all optional
//       limit: { context, output }, reasoning, tool_call, release_date } } } }
//
// Three local copies are read, in priority order, and all three carry the SAME
// top-level shape, so a single loader handles them:
//   1. our own cache        <cacheDir>/models-dev.json   (written by refresh())
//   2. OpenCode's cache     ~/.cache/opencode/models.json (same file, already on
//      disk on any machine with opencode installed — free head start offline)
//   3. the shipped seed     src/pricing/seed-prices.json  (small, first-party
//      only, generated by scripts/generate-price-seed.js)
// The seed exists so a fresh install with no network and no opencode still
// prices the twelve providers an Auto route actually picks between.
//
// Everything here is defensive by construction: a lookup NEVER throws and
// NEVER blocks on the network (it lazily reads the best local copy on first
// use); a refresh NEVER rejects (failures land in status().lastError while the
// previous table keeps serving). Callers therefore do not need try/catch, which
// is the whole point of putting the price question behind one interface.
//
// All returned objects are frozen: a caller cannot mutate the shared table by
// accident, so two routers comparing prices always see the same numbers.

const os = require('node:os');
const path = require('node:path');

const DEFAULT_REMOTE_URL = 'https://models.dev/api.json';

// Providers that publish a model themselves, in the order an Auto router should
// trust them. Several keys are the SAME model resold by an aggregator, and the
// aggregator's price is not the canonical one, so a first-party hit wins over
// an aggregator that carries the identical id (the aggregator copy is also the
// one that silently disappears when a reseller drops a model).
//
// 'zai' (Z.ai, international) and 'zhipuai' (Zhipu CN) are the same family on
// two endpoints — both stay listed, because a session's lane may be either.
const FIRST_PARTY_PROVIDERS = Object.freeze([
  'anthropic', 'openai', 'google', 'deepseek', 'zhipuai', 'zai',
  'moonshotai', 'alibaba', 'xai', 'mistral', 'minimax',
]);

const DEFAULT_REFRESH_INTERVAL_MS = 12 * 60 * 60 * 1000; // twice a day is plenty for a price catalog
const DEFAULT_TIMEOUT_MS = 20000;
// A remote payload that prices fewer models than this is not a price catalog:
// an error page that happens to parse as JSON, a truncated download, or an
// upstream schema change. Rejecting it keeps the previous table (see refresh).
const MIN_PRICED_MODELS = 50;
const START_DELAY_MS = 30000;      // never fetch inside the boot path
const STAT_THROTTLE_MS = 60000;    // at most one stat round per minute
const LAST_ERROR_MAX = 300;

// ~/.multicc/pricing by default; MULTICC_PRICING_CACHE_DIR exists so tests and
// isolated installs can point the cache at a temp/private root instead.
function defaultCacheDir() {
  return process.env.MULTICC_PRICING_CACHE_DIR || path.join(os.homedir(), '.multicc', 'pricing');
}

function defaultOpenCodeCachePath() {
  return path.join(os.homedir(), '.cache', 'opencode', 'models.json');
}

// A '~'-prefixed path is what a human writes; fs would treat it as a literal
// directory named '~'. Expand it here so both spellings work.
function expandHome(filePath) {
  const value = String(filePath || '');
  if (!value.startsWith('~')) return value;
  return path.join(os.homedir(), value.slice(1));
}

// None of null/undefined/'' may become 0 here: Number(null) and Number('') are
// both 0, and a missing price that reads as "free" is the one mistake this
// module must never make — it would route traffic to a model on the strength of
// a field the catalog simply does not carry.
function toFinitePrice(value) {
  if (typeof value === 'number') return Number.isFinite(value) && value >= 0 ? value : null;
  if (typeof value === 'string' && value.trim()) {
    const number = Number(value);
    return Number.isFinite(number) && number >= 0 ? number : null;
  }
  return null;
}

// One number a router can sort on. Agent workloads are input-heavy (a long
// system prompt, tool results and file contents dominate a turn, and the
// completion is short), so input is weighted 0.75 and output 0.25 rather than
// the 50/50 a chat-only comparison would use.
//
// Rules: both known -> the weighted blend; only one known -> that one (a
// missing field is not evidence the model is free); neither -> null, which is
// also what "unpriced" means everywhere in this module.
function blendedPrice(cost) {
  const input = toFinitePrice(cost && cost.input);
  const output = toFinitePrice(cost && cost.output);
  if (input === null && output === null) return null;
  if (input === null) return output;
  if (output === null) return input;
  return input * 0.75 + output * 0.25;
}

const TRAILING_DATE = /-(\d{8}|\d{4}-\d{2}-\d{2})$/;

// Collapse the many spellings of one model onto one key: sessions name models
// the way their CLI does (`anthropic/claude-sonnet-4-5`, a platform adds a
// context suffix `[1m]`, a dated snapshot `-20251001`, a reseller a `:free`
// tag), while the catalog may know the model under any of those.
//
// Order matters: the bracket and ':' suffixes are stripped BEFORE the
// vendor-prefix split so `vendor/model:free` keeps its model part, and the
// slash split happens before the date strip so a date inside a vendor name
// cannot be mistaken for a snapshot suffix.
function normalizeModelId(id) {
  let value = String(id == null ? '' : id).trim().toLowerCase();
  if (!value) return '';
  value = value.replace(/\[[^\]]*\]$/, '').trim();   // 'claude-sonnet-4-5[1m]'
  value = value.replace(/:[^/:]*$/, '').trim();      // 'deepseek-chat:free'
  const slash = value.lastIndexOf('/');
  if (slash >= 0) value = value.slice(slash + 1).trim(); // 'openrouter/anthropic/x' -> 'x'
  value = value.replace(TRAILING_DATE, '').trim();   // 'claude-haiku-4-5-20251001'
  return value;
}

// Cheap enough to run on a 5 MB catalog (it only reads cost numbers), and the
// only validation refresh() does: does this payload actually price models?
function countPricedModels(catalog) {
  let count = 0;
  for (const provider of Object.values(catalog || {})) {
    if (!provider || typeof provider !== 'object') continue;
    const models = provider.models;
    if (!models || typeof models !== 'object') continue;
    for (const model of Object.values(models)) {
      if (!model || typeof model !== 'object') continue;
      if (blendedPrice(model.cost) !== null) count += 1;
    }
  }
  return count;
}

function pushRecord(map, key, record) {
  if (!key) return;
  const bucket = map.get(key);
  if (bucket) bucket.push(record);
  else map.set(key, [record]);
}

// Build the lookup indices once per load. Two keys per model (its literal id
// and its normalized id) plus a flat list for search; the cost objects are
// normalized here into camelCase so no caller ever sees the wire spelling
// (cache_read) and no caller re-parses `cost` again.
function buildIndex(catalog) {
  const providers = new Map();
  const byId = new Map();
  const byNormalized = new Map();
  const records = [];
  let modelCount = 0;
  let pricedCount = 0;

  for (const [providerKey, provider] of Object.entries(catalog || {})) {
    // '_meta' — the seed's provenance header. It is data, not a provider.
    if (!providerKey || providerKey.startsWith('_')) continue;
    if (!provider || typeof provider !== 'object') continue;
    const models = provider.models;
    if (!models || typeof models !== 'object') continue;
    let providerModels = 0;

    for (const [modelId, model] of Object.entries(models)) {
      if (!model || typeof model !== 'object') continue;
      modelCount += 1;
      providerModels += 1;
      const cost = {
        input: toFinitePrice(model.cost && model.cost.input),
        output: toFinitePrice(model.cost && model.cost.output),
        cacheRead: toFinitePrice(model.cost && model.cost.cache_read),
        cacheWrite: toFinitePrice(model.cost && model.cost.cache_write),
      };
      const limit = {
        context: toFinitePrice(model.limit && model.limit.context),
        output: toFinitePrice(model.limit && model.limit.output),
      };
      const blended = blendedPrice(cost);
      if (blended !== null) pricedCount += 1;
      const record = {
        providerKey,
        modelId: typeof model.id === 'string' && model.id ? model.id : modelId,
        name: typeof model.name === 'string' && model.name ? model.name : modelId,
        cost,
        limit,
        blended,
        priced: blended !== null,
      };
      records.push(record);
      pushRecord(byId, record.modelId.toLowerCase(), record);
      pushRecord(byNormalized, normalizeModelId(record.modelId), record);
    }

    if (providerModels) {
      providers.set(providerKey, Object.freeze({
        id: typeof provider.id === 'string' && provider.id ? provider.id : providerKey,
        name: typeof provider.name === 'string' && provider.name ? provider.name : providerKey,
        modelCount: providerModels,
      }));
    }
  }

  return { providers, byId, byNormalized, records, modelCount, pricedCount };
}

// Which of several providers carrying one id to answer with. Unpriced entries
// never win (a router cannot route on "unknown"), the caller's hint beats every
// other rule, then the first-party list decides, and only for an
// aggregator-vs-aggregator tie do we fall back to the median price — the median
// rather than the cheapest so a suspiciously cheap reseller entry cannot win by
// itself.
function pickBest(candidates, providerHint) {
  if (!candidates || !candidates.length) return null;
  const priced = candidates.filter(candidate => candidate.priced);
  if (!priced.length) return null;
  if (providerHint) {
    const hinted = priced.find(candidate => candidate.providerKey === providerHint);
    if (hinted) return hinted;
  }
  for (const key of FIRST_PARTY_PROVIDERS) {
    const hit = priced.find(candidate => candidate.providerKey === key);
    if (hit) return hit;
  }
  const sorted = priced.slice().sort((left, right) => (
    left.blended - right.blended || left.providerKey.localeCompare(right.providerKey)
  ));
  return sorted[Math.floor(sorted.length / 2)];
}

function createPriceTable(options = {}) {
  const fetchImpl = options.fetchImpl || globalThis.fetch;
  const fsImpl = options.fsImpl || require('node:fs');
  const now = typeof options.now === 'function' ? options.now : Date.now;
  const cacheDir = expandHome(options.cacheDir || defaultCacheDir());
  const opencodeCachePath = expandHome(options.opencodeCachePath || defaultOpenCodeCachePath());
  const seedPath = expandHome(options.seedPath || path.join(__dirname, 'seed-prices.json'));
  const remoteUrl = options.remoteUrl || DEFAULT_REMOTE_URL;
  const refreshIntervalMs = Number.isFinite(options.refreshIntervalMs)
    ? options.refreshIntervalMs
    : DEFAULT_REFRESH_INTERVAL_MS;
  const timeoutMs = Number.isFinite(options.timeoutMs) ? options.timeoutMs : DEFAULT_TIMEOUT_MS;
  const logger = options.logger || {};

  const cacheFile = path.join(cacheDir, 'models-dev.json');
  const metaFile = path.join(cacheDir, 'meta.json');

  // Everything mutable lives in here; the object handed back is frozen.
  const state = {
    loaded: false,
    source: null,
    sourceFile: null,
    sourceMtimeMs: 0,
    fetchedAt: null,
    index: buildIndex({}),
    lastError: null,
    lastStatCheckAt: 0,
    persisted: true,
  };
  let inflight = null;
  let startTimer = null;
  let intervalTimer = null;

  function log(level, message) {
    const sink = logger[level];
    if (typeof sink === 'function') sink(message);
  }

  function recordError(error) {
    state.lastError = String((error && error.message) || error).slice(0, LAST_ERROR_MAX);
  }

  function readMeta() {
    try {
      const meta = JSON.parse(fsImpl.readFileSync(metaFile, 'utf8'));
      return meta && typeof meta === 'object' && !Array.isArray(meta) ? meta : null;
    } catch (_) {
      return null;
    }
  }

  function statMtime(file) {
    try {
      return Number(fsImpl.statSync(file).mtimeMs) || 0;
    } catch (_) {
      return 0;
    }
  }

  // The freshness clock of the loaded data: our own cache remembers when the
  // remote copy was last confirmed (meta.json), everything else can only be as
  // fresh as the file it was read from.
  function fetchedAtFor(source, file, mtimeMs) {
    if (source === 'models.dev') {
      const meta = readMeta();
      if (meta && typeof meta.fetchedAt === 'string' && Number.isFinite(Date.parse(meta.fetchedAt))) {
        return meta.fetchedAt;
      }
    }
    const mtime = mtimeMs || statMtime(file);
    return mtime ? new Date(mtime).toISOString() : null;
  }

  // `persisted: false` marks a table that exists only in memory (a refresh that
  // downloaded fine but could not write its cache). The reload check below uses
  // it so an unwritable cache dir cannot make the next lookup throw the freshly
  // downloaded prices away in favour of an older local file.
  function applyCatalog({ catalog, source, file, mtimeMs, persisted = true }) {
    state.index = buildIndex(catalog);
    state.source = source;
    state.sourceFile = file;
    state.sourceMtimeMs = mtimeMs || statMtime(file);
    state.fetchedAt = fetchedAtFor(source, file, state.sourceMtimeMs);
    state.persisted = persisted;
  }

  function tryLoad({ source, file }) {
    if (!file) return false;
    let catalog = null;
    let mtimeMs = 0;
    try {
      catalog = JSON.parse(fsImpl.readFileSync(file, 'utf8'));
      mtimeMs = statMtime(file);
    } catch (error) {
      // A missing file is the normal case for the higher-priority sources; a
      // file that exists but does not parse is worth remembering, because the
      // next question is always "why are the prices stale".
      if (fsImpl.existsSync && fsImpl.existsSync(file)) {
        log('warn', `pricing: cannot read ${file}: ${(error && error.message) || error}`);
        if (!state.lastError) recordError(error);
      }
      return false;
    }
    if (!catalog || typeof catalog !== 'object' || Array.isArray(catalog)) return false;
    if (countPricedModels(catalog) === 0) return false;
    applyCatalog({ catalog, source, file, mtimeMs });
    return true;
  }

  // Priority walk, by stat only: used both for the initial load and for the
  // cheap "did a better file appear or did ours get newer" check.
  function pickSourceFile() {
    for (const candidate of [
      { source: 'models.dev', file: cacheFile },
      { source: 'opencode-cache', file: opencodeCachePath },
      { source: 'seed', file: seedPath },
    ]) {
      if (!candidate.file) continue;
      let stat = null;
      try {
        stat = fsImpl.statSync(candidate.file);
      } catch (_) {
        continue;
      }
      if (!stat || !stat.isFile()) continue;
      return { ...candidate, mtimeMs: Number(stat.mtimeMs) || 0 };
    }
    return null;
  }

  function loadFromDisk() {
    for (const candidate of [
      { source: 'models.dev', file: cacheFile },
      { source: 'opencode-cache', file: opencodeCachePath },
      { source: 'seed', file: seedPath },
    ]) {
      if (tryLoad(candidate)) return true;
    }
    // Nothing local is readable: keep serving an empty table (every lookup
    // answers null) instead of throwing on every call. A refresh can still
    // fill it in later.
    state.index = buildIndex({});
    state.source = null;
    state.sourceFile = null;
    state.sourceMtimeMs = 0;
    state.fetchedAt = null;
    return false;
  }

  // Lazy, synchronous, once per load. Marking `loaded` first means a broken
  // file cannot turn every subsequent lookup into another failed read.
  function ensureLoaded() {
    if (state.loaded) return;
    state.loaded = true;
    loadFromDisk();
    state.lastStatCheckAt = now();
  }

  // A refresh in another process (or a fresh `opencode` cache dropped by an
  // upgrade) must be picked up without a restart, but stat-ing three files on
  // every lookup is not free — hence the 60s throttle.
  function maybeReload() {
    const nowMs = now();
    if (nowMs - state.lastStatCheckAt < STAT_THROTTLE_MS) return;
    state.lastStatCheckAt = nowMs;
    if (state.source === 'models.dev' && !state.persisted) return; // freshest copy is memory-only
    const candidate = pickSourceFile();
    if (!candidate) return;
    if (candidate.file === state.sourceFile && candidate.mtimeMs <= state.sourceMtimeMs) return;
    loadFromDisk();
  }

  function lookup(model, { providerHint } = {}) {
    try {
      ensureLoaded();
      maybeReload();
      const query = typeof model === 'string' ? model.trim() : String(model == null ? '' : model).trim();
      if (!query) return null;

      // (a) the literal id, then (b) its normalized form. Only a priced entry
      // can match, so an id the catalog knows but does not price answers null
      // rather than a price-free shell a router would misread as "free".
      // A vendor-prefixed id ("anthropic/claude-sonnet-4-5") names its first
      // party: that vendor's own list price wins over a reseller that happens
      // to publish the same literal id with a markup.
      const slash = query.indexOf('/');
      const vendor = slash > 0 ? query.slice(0, slash).toLowerCase() : '';
      const firstParty = !providerHint && FIRST_PARTY_PROVIDERS.includes(vendor)
        ? (state.index.byNormalized.get(normalizeModelId(query)) || [])
          .find(candidate => candidate.priced && candidate.providerKey === vendor) : null;
      let matchedBy = firstParty ? 'normalized' : 'exact';
      let record = firstParty || pickBest(state.index.byId.get(query.toLowerCase()), providerHint);
      if (!record) {
        matchedBy = 'normalized';
        const normalized = normalizeModelId(query);
        record = normalized ? pickBest(state.index.byNormalized.get(normalized), providerHint) : null;
      }
      if (!record) return null;

      return Object.freeze({
        model: record.modelId,
        query,
        providerKey: record.providerKey,
        input: record.cost.input,
        output: record.cost.output,
        cacheRead: record.cost.cacheRead,
        cacheWrite: record.cost.cacheWrite,
        blended: record.blended,
        context: record.limit.context,
        source: state.source,
        matchedBy,
        fetchedAt: state.fetchedAt,
      });
    } catch (_) {
      return null; // lookup is a question, not a transaction — never throw
    }
  }

  function lookupMany(models) {
    const prices = {};
    for (const model of Array.isArray(models) ? models : []) {
      if (typeof model !== 'string' || !model.trim()) continue;
      const key = model.trim();
      prices[key] = lookup(key);
    }
    return prices;
  }

  function status() {
    try {
      ensureLoaded();
    } catch (_) { /* status must not throw either */ }
    const index = state.index;
    const fetchedAtMs = state.fetchedAt ? Date.parse(state.fetchedAt) : NaN;
    return Object.freeze({
      source: state.source,
      fetchedAt: state.fetchedAt,
      modelCount: index ? index.modelCount : 0,
      providerCount: index ? index.providers.size : 0,
      pricedCount: index ? index.pricedCount : 0,
      // Two intervals, not one: a single missed refresh must not make a working
      // table look broken to whatever monitors this status.
      stale: !Number.isFinite(fetchedAtMs) || (now() - fetchedAtMs) > refreshIntervalMs * 2,
      lastError: state.lastError,
      refreshing: Boolean(inflight),
      remoteUrl,
    });
  }

  function search(q, { limit = 20 } = {}) {
    try {
      ensureLoaded();
      maybeReload();
      const needle = String(q == null ? '' : q).trim().toLowerCase();
      const capped = Math.max(1, Math.min(Number.isFinite(limit) ? Math.floor(limit) : 20, 200));
      if (!needle) return [];
      const hits = [];
      for (const record of state.index.records) {
        if (record.modelId.toLowerCase().includes(needle) || record.name.toLowerCase().includes(needle)) {
          hits.push(record);
        }
      }
      // Priced first (a caller comparing cost has no use for a shell), then
      // cheapest first, then by id so the order is stable across loads.
      hits.sort((left, right) => (
        (left.priced ? 0 : 1) - (right.priced ? 0 : 1)
        || (left.blended === null ? Infinity : left.blended) - (right.blended === null ? Infinity : right.blended)
        || left.modelId.localeCompare(right.modelId)
        || left.providerKey.localeCompare(right.providerKey)
      ));
      return hits.slice(0, capped).map(record => Object.freeze({
        model: record.modelId,
        name: record.name,
        providerKey: record.providerKey,
        input: record.cost.input,
        output: record.cost.output,
        cacheRead: record.cost.cacheRead,
        cacheWrite: record.cost.cacheWrite,
        blended: record.blended,
        context: record.limit.context,
        priced: record.priced,
        source: state.source,
        fetchedAt: state.fetchedAt,
      }));
    } catch (_) {
      return [];
    }
  }

  function writeAtomic(file, data) {
    fsImpl.mkdirSync(path.dirname(file), { recursive: true });
    // Write-then-rename: a concurrent reader (or a crash) can never observe a
    // half-written catalog, which is the failure mode that made an old build
    // treat every model as unpriced after a killed download.
    const tmp = `${file}.tmp-${process.pid}-${Date.now()}`;
    fsImpl.writeFileSync(tmp, data);
    fsImpl.renameSync(tmp, file);
  }

  function responseEtag(response) {
    try {
      const headers = response && response.headers;
      const value = headers && typeof headers.get === 'function' ? headers.get('etag') : null;
      return typeof value === 'string' && value ? value : null;
    } catch (_) {
      return null;
    }
  }

  async function performRefresh(force) {
    ensureLoaded();
    const controller = typeof AbortController === 'function' ? new AbortController() : null;
    let timer = null;
    if (controller) {
      // This timer must stay ref'd: when the fetch itself wedges (or an
      // injected fetch settles only via the abort), it is the ONLY thing that
      // can settle the refresh promise. An unref'd timer lets the event loop
      // drain first, leaving refresh() pending forever in an otherwise idle
      // process. It is cleared in finally the moment the fetch settles, so a
      // healthy refresh never holds the process open.
      timer = setTimeout(() => controller.abort(), timeoutMs);
    }
    try {
      const meta = readMeta();
      const storedEtag = meta && typeof meta.etag === 'string' && meta.etag ? meta.etag : null;
      const headers = { accept: 'application/json' };
      // force means "do not let a 304 answer for us" — the conditional request
      // is usually the cheap path, but a manual refresh must be able to prove
      // the upstream copy parses.
      if (!force && storedEtag) headers['if-none-match'] = storedEtag;

      const response = await fetchImpl(remoteUrl, controller ? { headers, signal: controller.signal } : { headers });
      const statusCode = Number(response && response.status);

      if (statusCode === 304) {
        // Unchanged upstream: only the freshness clock moves.
        const fetchedAt = new Date(now()).toISOString();
        const etag = responseEtag(response) || storedEtag;
        try {
          writeAtomic(metaFile, JSON.stringify({ etag, fetchedAt, url: remoteUrl }));
        } catch (error) {
          log('warn', `pricing: meta write failed: ${(error && error.message) || error}`);
        }
        state.fetchedAt = fetchedAt;
        state.lastError = null;
        state.lastStatCheckAt = now();
        log('info', `pricing: remote catalog unchanged (${state.index.pricedCount} priced models)`);
        return;
      }
      if ((response && response.ok === false) || (Number.isFinite(statusCode) && statusCode >= 400)) {
        throw new Error(`HTTP ${Number.isFinite(statusCode) ? statusCode : 'error'}`);
      }

      const text = response && typeof response.text === 'function'
        ? await response.text()
        : String((response && response.body) || '');
      let catalog = null;
      try {
        catalog = JSON.parse(text);
      } catch (_) {
        throw new Error('remote payload is not JSON');
      }
      if (!catalog || typeof catalog !== 'object' || Array.isArray(catalog)) {
        throw new Error('remote payload is not a provider catalog');
      }
      const priced = countPricedModels(catalog);
      if (priced < MIN_PRICED_MODELS) {
        // Keep whatever we already had. Overwriting a working table with an
        // error page is strictly worse than serving a 12-hour-old price.
        throw new Error(`remote payload rejected: only ${priced} priced model(s)`);
      }

      const fetchedAt = new Date(now()).toISOString();
      const etag = responseEtag(response) || storedEtag;
      let persisted = true;
      try {
        writeAtomic(cacheFile, text);
        writeAtomic(metaFile, JSON.stringify({ etag, fetchedAt, url: remoteUrl }));
      } catch (error) {
        // An unwritable cache dir is a real misconfiguration, but the data in
        // hand is good — adopt it in memory and say so, rather than discarding
        // a successful download.
        persisted = false;
        log('warn', `pricing: cache write failed: ${(error && error.message) || error}`);
      }
      applyCatalog({
        catalog, source: 'models.dev', file: cacheFile,
        mtimeMs: statMtime(cacheFile), persisted,
      });
      state.lastError = null;
      state.lastStatCheckAt = now();
      log('info', `pricing: refreshed ${state.index.pricedCount} priced models from ${remoteUrl}`
        + (persisted ? '' : ' (cache not persisted)'));
    } catch (error) {
      recordError(error);
      log('warn', `pricing: refresh failed: ${state.lastError}`);
    } finally {
      if (timer) clearTimeout(timer);
    }
  }

  // Never rejects, and concurrent callers share one in-flight request: a page
  // open in three tabs (or a monitor plus the router) must not download a 5 MB
  // catalog three times.
  function refresh({ force = false } = {}) {
    if (inflight) return inflight;
    inflight = performRefresh(Boolean(force)).then(
      () => { inflight = null; return status(); },
      () => { inflight = null; return status(); },
    );
    return inflight;
  }

  function isLocalFresh() {
    if (state.source !== 'models.dev' || !state.fetchedAt) return false;
    const fetchedAtMs = Date.parse(state.fetchedAt);
    return Number.isFinite(fetchedAtMs) && (now() - fetchedAtMs) < refreshIntervalMs;
  }

  function safeRefresh(force) {
    refresh({ force }).catch(() => {}); // refresh() already swallowed everything
  }

  function unref(timer) {
    if (timer && typeof timer.unref === 'function') timer.unref();
  }

  // Two timers on purpose: one delayed catch-up fetch when the local copy is
  // old (never during boot, when the machine is busy parsing other state), and
  // one steady interval afterwards. Both are unref'd so a short-lived CLI run
  // that happens to build a price table still exits.
  function start() {
    ensureLoaded();
    if (startTimer || intervalTimer) return;
    if (!isLocalFresh()) {
      startTimer = setTimeout(() => {
        startTimer = null;
        safeRefresh(false);
      }, START_DELAY_MS);
      unref(startTimer);
    }
    intervalTimer = setInterval(() => safeRefresh(false), refreshIntervalMs);
    unref(intervalTimer);
  }

  function stop() {
    if (startTimer) { clearTimeout(startTimer); startTimer = null; }
    if (intervalTimer) { clearInterval(intervalTimer); intervalTimer = null; }
  }

  return Object.freeze({
    lookup, lookupMany, status, refresh, search, start, stop,
    // Exposed for diagnostics/tests: the paths this table actually reads and
    // the interval it considers "fresh".
    cacheFile, metaFile, refreshIntervalMs,
  });
}

// Process-wide singleton. Every caller (routes, Auto router, quota UI) asks for
// the same table so one download and one index serve all of them.
let shared = null;

function sharedPriceTable() {
  if (!shared) {
    shared = createPriceTable();
    // MULTICC_PRICE_TABLE_OFFLINE=1 keeps the table read-only: handy for a
    // deterministic test/dev process that must not touch the network.
    if (process.env.MULTICC_PRICE_TABLE_OFFLINE !== '1') shared.start();
  }
  return shared;
}

module.exports = {
  createPriceTable,
  sharedPriceTable,
  blendedPrice,
  normalizeModelId,
  FIRST_PARTY_PROVIDERS,
  DEFAULT_REMOTE_URL,
};
