'use strict';

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const sourceDir = path.join(root, 'app', 'assets', 'i18n');
const output = path.join(root, 'public', 'i18n-catalog.js');

function readCatalog(locale) {
  const file = path.join(sourceDir, `${locale}.json`);
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

const catalogs = { zh: readCatalog('zh'), en: readCatalog('en') };
const banner = '// Generated by scripts/generate-i18n.js. Do not edit directly.\n';
const body = `window.MULTICC_I18N_CATALOG = ${JSON.stringify(catalogs, null, 2)};\n`;
fs.writeFileSync(output, banner + body);
console.log(`Generated ${path.relative(root, output)} (${Object.keys(catalogs.zh).length} keys)`);
